package samuraiarmor;

import javax.swing.*;

public class AdicionarStock extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdicionarStock.class.getName());

    /**
     * Creates new form AdicionarStock
     */
    public AdicionarStock() {
        initComponents();
        setTitle("Adicionar ao Stock");
        setSize(300, 220);
        setLocationRelativeTo(null);
        setLayout(null);

        JLabel lblId = new JLabel("ID Material:");
        JTextField txtId = new JTextField();
        JLabel lblQuantidade = new JLabel("Quantidade:");
        JTextField txtQuantidade = new JTextField();
        JButton btnAdicionar = new JButton("Adicionar");
        JButton btnVoltar = new JButton("Voltar");

        lblId.setBounds(20, 20, 100, 25);
        txtId.setBounds(120, 20, 140, 25);
        lblQuantidade.setBounds(20, 60, 100, 25);
        txtQuantidade.setBounds(120, 60, 140, 25);
        btnAdicionar.setBounds(30, 120, 110, 30);
        btnVoltar.setBounds(150, 120, 110, 30);

        btnAdicionar.addActionListener(e ->{
            try {
                int id = Integer.parseInt(txtId.getText());
                int quantidade = Integer.parseInt(txtQuantidade.getText());

                // Debug: ver quantos materiais existem
                System.out.println("Total de materiais: " + Loja.materiais.size());

                for (Material m : Loja.materiais) {
                    // Debug: ver os IDs que estão a ser comparados
                    System.out.println("Comparando ID: " + m.getId() + " com " + id);

                    if (m.getId() == id) {
                        m.atualizarStock(quantidade);
                        JOptionPane.showMessageDialog(this, "Stock atualizado!");
                        return;
                    }
                }
                JOptionPane.showMessageDialog(this, "Material não encontrado!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID e Quantidade devem ser números!");
            }
        });

        btnVoltar.addActionListener(e -> dispose());

        add(lblId);
        add(txtId);
        add(lblQuantidade);
        add(txtQuantidade);
        add(btnAdicionar);
        add(btnVoltar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdicionarStock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
