package samuraiarmor;

import javax.swing.*;
public class CriarEcomenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CriarEcomenda.class.getName());
    public CriarEcomenda() {
        initComponents();
        setTitle("Criar Encomenda");
        setSize(350, 260);
        setLocationRelativeTo(null);
        setLayout(null);

        JLabel lblCliente = new JLabel("Cliente:");
        JTextField txtCliente = new JTextField();
        JLabel lblMorada = new JLabel("Morada:");
        JTextField txtMorada = new JTextField();
        JLabel lblProduto = new JLabel("ID Produto:");
        JTextField txtProduto = new JTextField();
        JLabel lblQuantidade = new JLabel("Quantidade:");
        JTextField txtQuantidade = new JTextField();
        JButton btnCriar = new JButton("Criar");
        JButton btnVoltar = new JButton("Voltar");

        lblCliente.setBounds(20, 20, 100, 25);
        txtCliente.setBounds(120, 20, 180, 25);
        lblMorada.setBounds(20, 50, 100, 25);
        txtMorada.setBounds(120, 50, 180, 25);
        lblProduto.setBounds(20, 80, 100, 25);
        txtProduto.setBounds(120, 80, 180, 25);
        lblQuantidade.setBounds(20, 110, 100, 25);
        txtQuantidade.setBounds(120, 110, 180, 25);
        btnCriar.setBounds(50, 160, 100, 30);
        btnVoltar.setBounds(180, 160, 100, 30);

        btnCriar.addActionListener(e -> {
            try {
                String cliente = txtCliente.getText();
                String morada = txtMorada.getText();
                int idProduto = Integer.parseInt(txtProduto.getText());
                int quantidade = Integer.parseInt(txtQuantidade.getText());

                // Validações básicas
                if (cliente.trim().isEmpty() || morada.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
                    return;
                }

                // Procurar o material
                Material materialEncontrado = null;
                for (Material m : Loja.materiais) {
                    if (m.getId() == idProduto) {
                        materialEncontrado = m;
                        break;
                    }
                }

                // Verificar se o produto existe
                if (materialEncontrado == null) {
                    JOptionPane.showMessageDialog(this, "Produto não encontrado!");
                    return;
                }

                // Verificar se há stock suficiente
                if (materialEncontrado.getStock() < quantidade) {
                    JOptionPane.showMessageDialog(this, 
                        "Stock insuficiente! Disponível: " + materialEncontrado.getStock());
                    return;
                }

                // Diminuir o stock (usa valor negativo)
                materialEncontrado.atualizarStock(-quantidade);

                // Criar encomenda
                Encomenda encomenda = new Encomenda(cliente, morada, 
                    materialEncontrado.getMarca() + " - " + materialEncontrado.getClass().getSimpleName(), 
                    quantidade);
                Loja.encomendas.add(encomenda);

                JOptionPane.showMessageDialog(this, "Encomenda criada com sucesso!\nStock atualizado!");
                dispose();

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID do Produto e Quantidade devem ser números válidos!");
            }
        });

        btnVoltar.addActionListener(e -> dispose());

        add(lblCliente);
        add(txtCliente);
        add(lblMorada);
        add(txtMorada);
        add(lblProduto);
        add(txtProduto);
        add(lblQuantidade);
        add(txtQuantidade);
        add(btnCriar);
        add(btnVoltar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CriarEcomenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
