package samuraiarmor;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class VerStock extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VerStock.class.getName());
    public VerStock() {
        initComponents();
        setTitle("Stock - Samurai Armor");
        setSize(700, 350);
        setLocationRelativeTo(null);
        setLayout(null);

        String[] colunas = {
            "ID", "Marca", "Stock", "Tamanho",
            "Cor", "Preço (€)", "Tipo"
        };

        DefaultTableModel model = new DefaultTableModel(colunas, 0);
        JTable tabela = new JTable(model);

        for (Material m : Loja.materiais) {
            String tipo = m.getClass().getSimpleName(); // Obtém o tipo (Luvas, Capacete, etc.)

            model.addRow(new Object[]{
                m.getId(),
                m.getMarca(),
                m.getStock(),
                m.getTamanho(),
                m.getCor(),
                m.getPreco(),
                tipo
            });
        }

        JScrollPane scroll = new JScrollPane(tabela);
        scroll.setBounds(20, 20, 650, 220);

        JButton btnVoltar = new JButton("Voltar");
        btnVoltar.setBounds(300, 260, 100, 30);
        btnVoltar.addActionListener(e -> dispose());

        add(scroll);
        add(btnVoltar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VerStock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
